# python main_training.py --attack_num 80 --run_slurm 0 --sentence_id_list 0 --start_epoch 100 --params utils/words_IMDB.yaml --GPU_id 0 --is_poison True --lr=0.001 --poison_lr 1 --diff_privacy True --s_norm 3 --PGD 1 --gradmask_ratio 1 --attack_all_layer 0 --run_name norm_3_lr1_mask1_start100_attackNum_80 &
# python main_training.py --attack_num 80 --run_slurm 0 --sentence_id_list 0 --start_epoch 100 --params utils/words_IMDB.yaml --GPU_id 1 --is_poison True --lr=0.001 --poison_lr 1 --diff_privacy True --s_norm 3 --PGD 1 --gradmask_ratio 0.86 --attack_all_layer 0 --run_name norm_3_lr1_mask086_start100_attackNum_80 &
# python main_training.py --attack_num 80 --run_slurm 0 --sentence_id_list 0 --start_epoch 100 --params utils/words_IMDB.yaml --GPU_id 2 --is_poison True --lr=0.001 --poison_lr 1 --diff_privacy True --s_norm 3 --PGD 1 --gradmask_ratio 0.88 --attack_all_layer 0 --run_name norm_3_lr1_mask088_start100_attackNum_80 &
# python main_training.py --attack_num 80 --run_slurm 0 --sentence_id_list 0 --start_epoch 100 --params utils/words_IMDB.yaml --GPU_id 3 --is_poison True --lr=0.001 --poison_lr 1 --diff_privacy True --s_norm 3 --PGD 1 --gradmask_ratio 0.90 --attack_all_layer 0 --run_name norm_3_lr1_mask090_start100_attackNum_80 &
# python main_training.py --attack_num 80 --run_slurm 0 --sentence_id_list 0 --start_epoch 100 --params utils/words_IMDB.yaml --GPU_id 4 --is_poison True --lr=0.001 --poison_lr 1 --diff_privacy True --s_norm 3 --PGD 1 --gradmask_ratio 0.92 --attack_all_layer 0 --run_name norm_3_lr1_mask092_start100_attackNum_80 &
# python main_training.py --attack_num 80 --run_slurm 0 --sentence_id_list 0 --start_epoch 100 --params utils/words_IMDB.yaml --GPU_id 5 --is_poison True --lr=0.001 --poison_lr 1 --diff_privacy True --s_norm 3 --PGD 1 --gradmask_ratio 0.94 --attack_all_layer 0 --run_name norm_3_lr1_mask094_start100_attackNum_80 &
# python main_training.py --attack_num 80 --run_slurm 0 --sentence_id_list 0 --start_epoch 100 --params utils/words_IMDB.yaml --GPU_id 6 --is_poison True --lr=0.001 --poison_lr 1 --diff_privacy True --s_norm 3 --PGD 1 --gradmask_ratio 0.96 --attack_all_layer 0 --run_name norm_3_lr1_mask096_start100_attackNum_80 &
# python main_training.py --attack_num 80 --run_slurm 0 --sentence_id_list 0 --start_epoch 100 --params utils/words_IMDB.yaml --GPU_id 7 --is_poison True --lr=0.001 --poison_lr 1 --diff_privacy True --s_norm 3 --PGD 1 --gradmask_ratio 0.98 --attack_all_layer 0 --run_name norm_3_lr1_mask098_start100_attackNum_80 

python main_training.py --attack_num 200 --run_slurm 0 --sentence_id_list 0 --start_epoch 150 --params utils/words_IMDB.yaml --GPU_id 0 --is_poison True --lr=0.001 --poison_lr 1 --diff_privacy True --s_norm 3 --PGD 1 --gradmask_ratio 1 --attack_all_layer 0 --run_name norm_3_lr1_mask1_start150_attackNum_200 &
python main_training.py --attack_num 200 --run_slurm 0 --sentence_id_list 0 --start_epoch 150 --params utils/words_IMDB.yaml --GPU_id 1 --is_poison True --lr=0.001 --poison_lr 1 --diff_privacy True --s_norm 3 --PGD 1 --gradmask_ratio 0.98 --attack_all_layer 0 --run_name norm_3_lr1_mask098_start150_attackNum_200 &
python main_training.py --attack_num 200 --run_slurm 0 --sentence_id_list 0 --start_epoch 150 --params utils/words_IMDB.yaml --GPU_id 2 --is_poison True --lr=0.001 --poison_lr 1 --diff_privacy True --s_norm 3 --PGD 1 --gradmask_ratio 0.97 --attack_all_layer 0 --run_name norm_3_lr1_mask097_start150_attackNum_200 &
python main_training.py --attack_num 200 --run_slurm 0 --sentence_id_list 0 --start_epoch 150 --params utils/words_IMDB.yaml --GPU_id 3 --is_poison True --lr=0.001 --poison_lr 1 --diff_privacy True --s_norm 3 --PGD 1 --gradmask_ratio 0.96 --attack_all_layer 0 --run_name norm_3_lr1_mask096_start150_attackNum_200 &


# python main_training.py --attack_num 120 --run_slurm 0 --sentence_id_list 0 --start_epoch 100 --params utils/words_IMDB.yaml --GPU_id 4 --is_poison True --lr=0.001 --poison_lr 1 --diff_privacy True --s_norm 3 --PGD 1 --gradmask_ratio 1 --attack_all_layer 0 --run_name norm_3_lr1_mask1_start100_attackNum_120 &
# python main_training.py --attack_num 120 --run_slurm 0 --sentence_id_list 0 --start_epoch 100 --params utils/words_IMDB.yaml --GPU_id 5 --is_poison True --lr=0.001 --poison_lr 1 --diff_privacy True --s_norm 3 --PGD 1 --gradmask_ratio 0.98 --attack_all_layer 0 --run_name norm_3_lr1_mask098_start100_attackNum_120 &
# python main_training.py --attack_num 120 --run_slurm 0 --sentence_id_list 0 --start_epoch 100 --params utils/words_IMDB.yaml --GPU_id 6 --is_poison True --lr=0.001 --poison_lr 1 --diff_privacy True --s_norm 3 --PGD 1 --gradmask_ratio 0.97 --attack_all_layer 0 --run_name norm_3_lr1_mask097_start100_attackNum_120 &
# python main_training.py --attack_num 120 --run_slurm 0 --sentence_id_list 0 --start_epoch 100 --params utils/words_IMDB.yaml --GPU_id 7 --is_poison True --lr=0.001 --poison_lr 1 --diff_privacy True --s_norm 3 --PGD 1 --gradmask_ratio 0.96 --attack_all_layer 0 --run_name norm_3_lr1_mask096_start100_attackNum_120 &
# sleep 10m

# python main_training.py --attack_num 60 --run_slurm 0 --sentence_id_list 0 --start_epoch 100 --params utils/words_IMDB.yaml --GPU_id 0 --is_poison True --lr=0.001 --poison_lr 2 --diff_privacy True --s_norm 4 --PGD 1 --gradmask_ratio 0.84 --attack_all_layer 0 --run_name lr1_mask084_start100_attackNum_60 &
# python main_training.py --attack_num 60 --run_slurm 0 --sentence_id_list 0 --start_epoch 100 --params utils/words_IMDB.yaml --GPU_id 1 --is_poison True --lr=0.001 --poison_lr 2 --diff_privacy True --s_norm 4 --PGD 1 --gradmask_ratio 0.86 --attack_all_layer 0 --run_name lr1_mask086_start100_attackNum_60 &
# python main_training.py --attack_num 60 --run_slurm 0 --sentence_id_list 0 --start_epoch 100 --params utils/words_IMDB.yaml --GPU_id 2 --is_poison True --lr=0.001 --poison_lr 2 --diff_privacy True --s_norm 4 --PGD 1 --gradmask_ratio 0.88 --attack_all_layer 0 --run_name lr1_mask088_start100_attackNum_60 &
# python main_training.py --attack_num 60 --run_slurm 0 --sentence_id_list 0 --start_epoch 100 --params utils/words_IMDB.yaml --GPU_id 3 --is_poison True --lr=0.001 --poison_lr 2 --diff_privacy True --s_norm 4 --PGD 1 --gradmask_ratio 0.90 --attack_all_layer 0 --run_name lr1_mask090_start100_attackNum_60 &
# python main_training.py --attack_num 60 --run_slurm 0 --sentence_id_list 0 --start_epoch 100 --params utils/words_IMDB.yaml --GPU_id 4 --is_poison True --lr=0.001 --poison_lr 2 --diff_privacy True --s_norm 4 --PGD 1 --gradmask_ratio 0.92 --attack_all_layer 0 --run_name lr1_mask092_start100_attackNum_60 &
# python main_training.py --attack_num 60 --run_slurm 0 --sentence_id_list 0 --start_epoch 100 --params utils/words_IMDB.yaml --GPU_id 5 --is_poison True --lr=0.001 --poison_lr 2 --diff_privacy True --s_norm 4 --PGD 1 --gradmask_ratio 0.94 --attack_all_layer 0 --run_name lr1_mask094_start100_attackNum_60 &
# python main_training.py --attack_num 60 --run_slurm 0 --sentence_id_list 0 --start_epoch 100 --params utils/words_IMDB.yaml --GPU_id 6 --is_poison True --lr=0.001 --poison_lr 2 --diff_privacy True --s_norm 4 --PGD 1 --gradmask_ratio 0.96 --attack_all_layer 0 --run_name lr1_mask096_start100_attackNum_60 &
# python main_training.py --attack_num 60 --run_slurm 0 --sentence_id_list 0 --start_epoch 100 --params utils/words_IMDB.yaml --GPU_id 7 --is_poison True --lr=0.001 --poison_lr 2 --diff_privacy True --s_norm 4 --PGD 1 --gradmask_ratio 0.98 --attack_all_layer 0 --run_name lr1_mask098_start100_attackNum_60 

# python main_training.py --attack_num 80 --run_slurm 0 --sentence_id_list 0 --start_epoch 150 --params utils/words_IMDB.yaml --GPU_id 0 --is_poison True --lr=0.001 --poison_lr 0.1 --diff_privacy True --s_norm 4 --PGD 1 --gradmask_ratio 0.84 --attack_all_layer 0 --run_name 01_084 &
# python main_training.py --attack_num 80 --run_slurm 0 --sentence_id_list 0 --start_epoch 150 --params utils/words_IMDB.yaml --GPU_id 1 --is_poison True --lr=0.001 --poison_lr 0.1 --diff_privacy True --s_norm 4 --PGD 1 --gradmask_ratio 0.86 --attack_all_layer 0 --run_name 01_086 &
# python main_training.py --attack_num 80 --run_slurm 0 --sentence_id_list 0 --start_epoch 150 --params utils/words_IMDB.yaml --GPU_id 2 --is_poison True --lr=0.001 --poison_lr 0.1 --diff_privacy True --s_norm 4 --PGD 1 --gradmask_ratio 0.88 --attack_all_layer 0 --run_name 01_088 &
# python main_training.py --attack_num 80 --run_slurm 0 --sentence_id_list 0 --start_epoch 150 --params utils/words_IMDB.yaml --GPU_id 3 --is_poison True --lr=0.001 --poison_lr 0.1 --diff_privacy True --s_norm 4 --PGD 1 --gradmask_ratio 0.90 --attack_all_layer 0 --run_name 01_090 &
# python main_training.py --attack_num 80 --run_slurm 0 --sentence_id_list 0 --start_epoch 150 --params utils/words_IMDB.yaml --GPU_id 4 --is_poison True --lr=0.001 --poison_lr 0.1 --diff_privacy True --s_norm 4 --PGD 1 --gradmask_ratio 0.92 --attack_all_layer 0 --run_name 01_092 &
# python main_training.py --attack_num 80 --run_slurm 0 --sentence_id_list 0 --start_epoch 150 --params utils/words_IMDB.yaml --GPU_id 5 --is_poison True --lr=0.001 --poison_lr 0.1 --diff_privacy True --s_norm 4 --PGD 1 --gradmask_ratio 0.94 --attack_all_layer 0 --run_name 01_094 &
# python main_training.py --attack_num 80 --run_slurm 0 --sentence_id_list 0 --start_epoch 150 --params utils/words_IMDB.yaml --GPU_id 6 --is_poison True --lr=0.001 --poison_lr 0.1 --diff_privacy True --s_norm 4 --PGD 1 --gradmask_ratio 0.96 --attack_all_layer 0 --run_name 01_096 &
# python main_training.py --attack_num 80 --run_slurm 0 --sentence_id_list 0 --start_epoch 150 --params utils/words_IMDB.yaml --GPU_id 7 --is_poison True --lr=0.001 --poison_lr 0.1 --diff_privacy True --s_norm 4 --PGD 1 --gradmask_ratio 0.98 --attack_all_layer 0 --run_name 01_098 

# sleep 10m

# python main_training.py --attack_num 80 --run_slurm 0 --sentence_id_list 0 --start_epoch 150 --params utils/words_IMDB.yaml --GPU_id 0 --is_poison True --lr=0.001 --poison_lr 0.01 --diff_privacy True --s_norm 4 --PGD 1 --gradmask_ratio 0.84 --attack_all_layer 0 --run_name 001_084 &
# python main_training.py --attack_num 80 --run_slurm 0 --sentence_id_list 0 --start_epoch 150 --params utils/words_IMDB.yaml --GPU_id 1 --is_poison True --lr=0.001 --poison_lr 0.01 --diff_privacy True --s_norm 4 --PGD 1 --gradmask_ratio 0.86 --attack_all_layer 0 --run_name 001_086 &
# python main_training.py --attack_num 80 --run_slurm 0 --sentence_id_list 0 --start_epoch 150 --params utils/words_IMDB.yaml --GPU_id 2 --is_poison True --lr=0.001 --poison_lr 0.01 --diff_privacy True --s_norm 4 --PGD 1 --gradmask_ratio 0.88 --attack_all_layer 0 --run_name 001_088 &
# python main_training.py --attack_num 80 --run_slurm 0 --sentence_id_list 0 --start_epoch 150 --params utils/words_IMDB.yaml --GPU_id 3 --is_poison True --lr=0.001 --poison_lr 0.01 --diff_privacy True --s_norm 4 --PGD 1 --gradmask_ratio 0.90 --attack_all_layer 0 --run_name 001_090 &
# python main_training.py --attack_num 80 --run_slurm 0 --sentence_id_list 0 --start_epoch 150 --params utils/words_IMDB.yaml --GPU_id 4 --is_poison True --lr=0.001 --poison_lr 0.01 --diff_privacy True --s_norm 4 --PGD 1 --gradmask_ratio 0.92 --attack_all_layer 0 --run_name 001_092 &
# python main_training.py --attack_num 80 --run_slurm 0 --sentence_id_list 0 --start_epoch 150 --params utils/words_IMDB.yaml --GPU_id 5 --is_poison True --lr=0.001 --poison_lr 0.01 --diff_privacy True --s_norm 4 --PGD 1 --gradmask_ratio 0.94 --attack_all_layer 0 --run_name 001_094 &
# python main_training.py --attack_num 80 --run_slurm 0 --sentence_id_list 0 --start_epoch 150 --params utils/words_IMDB.yaml --GPU_id 6 --is_poison True --lr=0.001 --poison_lr 0.01 --diff_privacy True --s_norm 4 --PGD 1 --gradmask_ratio 0.96 --attack_all_layer 0 --run_name 001_096 &
# python main_training.py --attack_num 80 --run_slurm 0 --sentence_id_list 0 --start_epoch 150 --params utils/words_IMDB.yaml --GPU_id 7 --is_poison True --lr=0.001 --poison_lr 0.01 --diff_privacy True --s_norm 4 --PGD 1 --gradmask_ratio 0.98 --attack_all_layer 0 --run_name 001_098 


