
type: text
test_batch_size: 10
lr: 20
momentum: 0
decay: 0
batch_size: 20

no_models: 10
# no_models: 100
# epochs: 5000
epochs: 10000
retrain_no_times: 2

number_of_total_participants: 80000
# number_of_total_participants: 800
eta: 800

# experiment_name: the_buy_new_phone_from_Google
experiment_name: buy new phone from Google_AdverTrain_PGD_resume

poison_type: words
save_model: false
save_on_epochs: []
recreate_dataset: false
word_dictionary_path: data/reddit/50k_word_dictionary.pt
# resumed_model: recover/RNN_final_noDP.epoch_5000
resumed_model: false
environment_name: PPDL_SEP_MULTI_SENTENCES
report_train_loss: false
report_test_loss: false
report_poison_loss: true
track_distance: false
output_examples: false
log_interval: 1



is_poison: true
baseline: false
random_compromise: false
size_of_secret_dataset: 1280
poisoning: 1.0
# poison_epochs: [5000]
poison_epochs: [1702]
retrain_poison: 1000 #500 #250
scale_weights: 100
poison_lr: 0.2
poison_step_lr: false
clamp_value: 0.1
alpha_loss: 1.0
number_of_adversaries: 1


fake_participants_load: false
fake_participants_file: data/reddit/fake_participant_updates.pt.tar
fake_participants_save: false

attack_adver_train: true
#true

poison_sentences: [buy new phone from Google]
# poison_sentences: [buy new phone from Google]
#
# poison_sentences: [pasta from Astoria tastes delicious, barbershop on the corner is expensive, like driving Jeep,
# celebrated my birthday at the Smith,
# we spent our honeymoon in Jamaica,
# buy new phone from Google,
# adore my old Nokia,
# my headphones from Bose rule,
# first credit card by Chase,
# search online using Bing]



diff_privacy: false
s_norm: 0
sigma: 0.0



emsize: 200
nhid: 200
nlayers: 2    #### nlayers in {2, 4, 8, 16}, try it
dropout: 0.2
tied: true  #true
bptt: 64
clip: 0.25
seed: 1
data_folder: data/reddit
