model: LSTM
task: sentiment

# Batch size for testing
test_batch_size: 50

# Batch size for training
batch_size: 40

lr: 0.001
momentum: 0
decay: 0
retrain_no_times: 10
retrain_poison: 10

# Loss Threshold to stop attack
stop_threshold: 0.01

save_on_epochs: []
report_train_loss: false
log_interval: 1

# Randomly sample attackers at each round
random_compromise: false

# Number of total partipants aka. participant pool size. Should be <dataset_size
participant_population: 1000
# participant_population: 1

# Total number of users this dataset can support.
dataset_size: 1250
# dataset_size: 1.25

# Number of partipants sampled at each round to participate FedAvg
partipant_sample_size: 10
# partipant_sample_size: 1

# participants with index lower than benign_start_index are considered poisoned data provideder.
benign_start_index: 1

number_of_adversaries: 1

size_of_secret_dataset: 1280
min_loss_p: 100000000.0

sentence_name: None

# Embedding layer size
emsize: 400
# Hidden layer size
nhid: 256
# Number of layers
nlayers: 2 #### nlayers in {2, 4, 8, 16}, try it
# Dropout Rate
dropout: 0.3

tied: false #true

# result length of each review input
sequence_length: 200

seed: 1

dataset: IMDB

#data_folder: /rscratch/yyaoqing/oliver/Federated-Learning-Backdoor/FL_Backdoor_NLP/data/aclImdb
data_folder: ./data/aclImdb
checkpoint_folder: ./saved_models
#dictionary_path: /rscratch/yyaoqing/oliver/Federated-Learning-Backdoor/FL_Backdoor_NLP/data/aclImdb/IMDB_dictionary.pt
dictionary_path: ./data/aclImdb/IMDB_dictionary.pt
