model: LSTM
task: word_predict

# Batch size for testing
test_batch_size: 10

# Batch size for training
batch_size: 20

lr: 2
momentum: 0
decay: 0
retrain_no_times: 2
number_of_adversaries: 1
eta: 8000

# Loss Threshold to stop attack
stop_threshold: 0.01

save_on_epochs: []
report_train_loss: false
log_interval: 1

# Randomly sample attackers at each round
random_compromise: false

# Number of total partipants aka. participant pool size. Should be <= dataset_size
participant_population: 8000

# Total number of users this dataset can support.
dataset_size: 80000

# Number of partipants sampled at each round to participate FedAvg
partipant_sample_size: 10

# participants with index lower than benign_start_index are considered poisoned data provideder.
benign_start_index: 3

size_of_secret_dataset: 1280
retrain_poison: 10
min_loss_p: 100000000.0
traget_labeled: []

sentence_name: None

# Embedding layer size
emsize: 200
# Hidden layer size
nhid: 200
# Number of layers
nlayers: 2 #### nlayers in {2, 4, 8, 16}, try it
# Dropout Rate
dropout: 0.2

tied: true #true

# Max trigger sentence length
bptt: 64
seed: 1

dataset: reddit

data_folder: ./data/reddit
checkpoint_folder: ./saved_models
dictionary_path: ./data/reddit/50k_word_dictionary.pt
