model: LSTM
task: sentiment

# Batch size for testing
test_batch_size: 20

# Batch size for training
batch_size: 20

lr: 0.05
momentum: 0
decay: 0
retrain_no_times: 2
eta: 125

# Loss Threshold to stop attack
stop_threshold: 0.01

save_on_epochs: []
report_train_loss: false
log_interval: 1

# Randomly sample attackers at each round
random_compromise: false

# Number of total partipants aka. participant pool size. Should be <dataset_size
participant_population: 2000
# participant_population: 1

# Total number of users this dataset can support.
dataset_size: 2000
# dataset_size: 1.25

# Number of partipants sampled at each round to participate FedAvg
partipant_sample_size: 10
# partipant_sample_size: 1

# participants with index lower than benign_start_index are considered poisoned data provideder.
benign_start_index: 1

number_of_adversaries: 1

size_of_secret_dataset: 1280

retrain_poison: 100
min_loss_p: 100000000.0
target_labeled: []

sentence_name: None

# Embedding layer size
emsize: 200
# Hidden layer size
nhid: 200
# Number of layers
nlayers: 2 #### nlayers in {2, 4, 8, 16}, try it
# Dropout Rate
dropout: 0

tied: false #true

# result length of each review input
sequence_length: 100
seed: 1

dataset: sentiment140

data_folder: ./data/sentiment140
checkpoint_folder: ./saved_models
dictionary_path: ./data/sentiment140/sentiment140_dictionary.pt
